### PR TITLE
setup project with react-redux linters and readme files

### PR DESCRIPTION
**Pull request by ram1117**
Hi, I have added the following in this pull request. Please review the changes.

1.Setup new react project using `create-react-app`
2.Add microverse readme template file
3.Add microverse react and redux linter configuration files

Here is a preview of the webpage

Peek 2023-02-13 15-43

### CODE REVIEW

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @ram1117,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### 1. You have implemented the wrong workflow. You should request merge to develop branch, not the main branch.
### 2. Most of your README sections contain dummy data from the template. Kindly update your README sections with information on the project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ram1117** [comment]
@TedLivist hi Teddy, thank you for the feedback. I did forget to use Gitflow. I will make the changes

**Comment by ram1117** [comment]
1.Use Gitflow, modifying this PR to be merged with `dev` branch.
2.Update Readme file and add LICENSE file.

**Review by julie-ify — APPROVED** [review]
Hi @ram1117,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ram1117** [comment]
Hi @julie-ify , thank you for the feedback

**Pull request merged**
